### ISSUE TITLE
Build failure with ghc 8.4

### ISSUE THREAD

**Issue by DanBurton** [redneb/hs-adler32#1] opened 2018-03-13 22:55 UTC
Add Semigroup instances for your monoids:

```
Building library for adler32-0.1.1.0..
[1 of 1] Compiling Data.Digest.Adler32 ( src/Data/Digest/Adler32.hs, dist/build/
Data/Digest/Adler32.o )

src/Data/Digest/Adler32.hs:63:26: error:
    • Could not deduce (Semigroup Adler32) arising from a use of ‘<>’
      from the context: Adler32Src a
        bound by the class declaration for ‘Adler32Src’
        at src/Data/Digest/Adler32.hs:52:7-16
    • In the second argument of ‘($)’, namely
        ‘makeAdler32 c (0 :: Word32) <> adler32' s’
      In the expression:
        extractAdler32 $ makeAdler32 c (0 :: Word32) <> adler32' s
      In an equation for ‘adler32Update’:
          adler32Update c s
            = extractAdler32 $ makeAdler32 c (0 :: Word32) <> adler32' s
   |
63 |         extractAdler32 $ makeAdler32 c (0 :: Word32) <> adler32' s
   |                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Data/Digest/Adler32.hs:138:46: error:
    • No instance for (Semigroup Adler32) arising from a use of ‘<>’
    • In the expression: c <> adler32' s
      In the first argument of ‘BL.foldlChunks’, namely
        ‘(\ c s -> c <> adler32' s)’
      In the expression: BL.foldlChunks (\ c s -> c <> adler32' s)
    |
138 |     adler32Update' = BL.foldlChunks (\c s -> c <> adler32' s)
    |                                              ^^^^^^^^^^^^^^^

src/Data/Digest/Adler32.hs:143:10: error:
    • No instance for (Semigroup Adler32)
        arising from the superclasses of an instance declaration
    • In the instance declaration for ‘Monoid Adler32’
    |
143 | instance Monoid Adler32 where
    |          ^^^^^^^^^^^^^^
```

Per this build failure, this package has been removed from the Stackage nightly build plan. To restore it, please open a PR on the Stackage GitHub repo as usual.

**Comment by redneb** [comment] 2018-03-15 08:41
Thanks for the report. The issue is fixed in 0.1.2.0.

**Closed as completed by redneb** 2018-03-15 08:41 UTC
